game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include
# [코드 작성] page 앱 폴더의 views.py 가져오기
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('game/', include('game.urls')),
    # [코드 작성] account 앱의 urls.py 연결
    path('account/', include('account.urls')),
    # [코드 작성] http://127.0.0.1:8000/ 경로로 접근할 때 index 페이지로 바로 접근할 수 있도록 경로 설정
    path('', views.index),
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.posting_create, name='posting_create'),
    path('list/', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    # [코드 작성] 댓글 삭제 기능을 동작하게 하는 url 작성 (posting_id, comment_id 인자 전달)
    path('<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

page/templates/page/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/index.css' %}">
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>
  
  <p>오늘의 목표</p>
  <ol>
    <li>새로운 앱을 생성해봅시다.</li>
    <li>회원 관련 기능(회원가입, 로그인, 로그아웃)을 추가해봅시다.</li>
    <li>글과 댓글 모델에 작성자를 추가해봅시다.</li>
  </ol>

  <img src="{% static 'images/walnut.jpg' %}" alt="walnut">
{% endblock %}

page/templates/page/posting_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_detail.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <div class="posting">
    <table class="posting__detail">
      <tr>
        <td class="posting__detail__title">{{posting.title}}</td>
        <td class="posting__detail__function">
          <div>
            <a class="button" href="{% url 'page:posting_update' posting.id %}">수정</a>
            <form action="{% url 'page:posting_delete' posting.id %}" method="post" onsubmit="return contentDelete()">
              {% csrf_token %}
              <input class="button" type="submit" value="삭제">
            </form>
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__content" colspan="2">
          <div class="content">
            <span class="content__space">{{posting.content|linebreaksbr}}</span>
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__function transparent" colspan="2">
          <div>
            <a class="button" href="{% url 'page:posting_list' %}">글 목록</a>
          </div>
        </td>
      </tr>
    </table>

    <table class="posting__comment">
      <tr>
        <th colspan="2">댓글 목록</th>
      </tr>
      <tr>
        <td class="posting__comment__create" colspan="2">
          <form action="" method="post">
            {% csrf_token %}
            <div>
              {{comment_form.as_div}}
              <input class="button" type="submit" value="작성">
            </div>
          </form>
        </td>
      </tr>
      {% for comment in comments %}
        <tr>
          <td class="posting__comment__content">
            <span class="content__space">{{comment.content|linebreaksbr}}</span>
          </td>
          <td class="posting__comment__delete" rowspan="2">
            <!-- [코드 추가] POST 방식으로 댓글 삭제 후 action을 이용해 url 이름이 comment_delete인 url로 이동 -->
            <form action="{% url 'page:comment_delete' posting_id=posting.id comment_id=comment.id %}" method="post" onsubmit="return contentDelete()">
              {% csrf_token %}
              <input type="submit" value="x">
            </form>
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="posting__comment__content" colspan="2">
            댓글이 아직 작성되지 않았습니다.
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date"></td>
        </tr>
        <tr>
          <td colspan="2">
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

  <script>
    const contents = document.getElementsByClassName("content__space")
    
    for (let i=0; i<contents.length; i++) {
      contents[i].innerHTML = contents[i].innerHTML.replace(/ /g, "&nbsp;");
    }

    function contentDelete() {
      const result = confirm("삭제하시겠습니까?");
      return result;
    }
  </script>
{% endblock %}

page/templates/page/posting_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_form.css' %}">
{% endblock %}

{% block body %}
  <h1>{{posting_type}}</h1>

  <div class="posting-form">
    <form action="" method="post">
      {% csrf_token %}
      {{posting_form.as_p}}
  
      <div class="posting-form__function--bottom">
        {% if posting %}
          <a class="button" href="{% url 'page:posting_detail' posting.id %}">취소</a>
        {% endif %}
        <input class="button" type="submit" value="등록">
      </div>
    </form>
  </div>
{% endblock %}

page/templates/page/posting_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_list.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="posting">
    <div class="posting__function--top">
      <a class="button" href="{% url 'page:posting_create' %}">글쓰기</a>
    </div>
  
    <table class="posting__list">
      <tr>
        <th class="index">번호</th>
        <th class="title">제목</th>
        <th class="date">날짜</th>
      </tr>
      {% for posting in postings reversed %}
        <tr>
          <td class="index">{{forloop.revcounter}}</td>
          <td class="title"><a href="{% url 'page:posting_detail' posting.id %}">{{posting.title}}</a></td>
          <td class="date">{{posting.date|date:'Y-m-d'}}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="index">-</td>
          <td class="title">글을 작성해주세요.</td>
          <td class="date">-</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}