game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include
# [코드 작성] page 앱 폴더의 views.py 가져오기
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('game/', include('game.urls')),
    # [코드 작성] account 앱의 urls.py 연결
    path('account/', include('account.urls')),
    # [코드 작성] http://127.0.0.1:8000/ 경로로 접근할 때 index 페이지로 바로 접근할 수 있도록 경로 설정
    path('', views.index),
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.posting_create, name='posting_create'),
    path('list/', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    # [코드 작성] 댓글 삭제 기능을 동작하게 하는 url 작성 (posting_id, comment_id 인자 전달)
    path('<int:posting_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="navbar">
    <span>
      <a href="{% url 'page:index' %}">
        <img class="navbar__logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
      </a>
    </span>
    <span>
      <a href="{% url 'page:posting_list' %}">글목록</a>
    </span>
    <span>
      <a href="{% url 'page:posting_create' %}">글쓰기</a>
    </span>
    <span>
      <a href="{% url 'game:game_list' %}">게임목록</a>
    </span>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>