game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon/create/', views.weapon_create, name='weapon_create'),
    path('weapon/list/', views.weapon_list, name='weapon_list'),
    path('adventure/home/', views.adventure_home, name='adventure_home'),
    path('weapon/get/', views.weapon_get, name='weapon_get'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include
# [코드 작성] page 앱 폴더의 views.py 가져오기
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('game/', include('game.urls')),
    # [코드 작성] account 앱의 urls.py 연결
    path('account/', include('account.urls')),
    # [코드 작성] http://127.0.0.1:8000/ 경로로 접근할 때 index 페이지로 바로 접근할 수 있도록 경로 설정
    path('', views.index),
]

game/models.py
from django.db import models

# Create your models here.
class Weapon(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()

    def __str__(self):
        return self.name

class Character(models.Model):
    nickname = models.CharField(max_length=20)
    weapon = models.ForeignKey(Weapon, on_delete=models.CASCADE, related_name='character_list', null=True, blank=True)

    def __str__(self):
        return self.nickname

game/forms.py
from django import forms
from .models import Weapon, Character

class WeaponForm(forms.ModelForm):
    name = forms.CharField(label='무기 이름')
    power = forms.IntegerField(label='무기 공격력')

    class Meta:
        model = Weapon
        fields = '__all__'

class CharacterForm(forms.ModelForm):
    nickname = forms.CharField(label="닉네임을 입력해주세요")

    class Meta:
        model = Character
        fields = ['nickname',]

game/views.py
from django.shortcuts import render, redirect
from random import *
from .models import Weapon, Character
from .forms import WeaponForm, CharacterForm

# Create your views here.
win = 0
draw = 0
lose = 0

def game_list(request):
    return render(request, 'game/game_list.html')

def rsp_select(request):
    global win, draw, lose
    context = {
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'game/rsp_select.html', context)

def rsp_result(request, pick):
    global win, draw, lose
    rsp = ['가위', '바위', '보']
    com = choice(rsp)

    if pick == com:
        result = '무승부'
        draw += 1
    elif (pick == '가위' and com == '보') or (pick == '바위' and com == '가위') or (pick == '보' and com == '바위'):
        result = '승리'
        win += 1
    else :
        result = '패배'
        lose += 1

    context = {
        'pick': pick,
        'com': com,
        'result': result,
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'game/rsp_result.html', context)

def rsp_reset(request):
    global win, draw, lose
    win, draw, lose = 0, 0, 0
    return redirect('game:rsp_select')

def weapon_create(request):
    if request.method == 'POST':
        weapon_form = WeaponForm(request.POST)
        
        if weapon_form.is_valid():
            weapon_form.save()
            return redirect('game:weapon_list')
    else:
        weapon_form = WeaponForm()
    
    context = {
        'weapon_form': weapon_form,
    }
    return render(request, 'game/weapon_form.html', context)

def weapon_list(request):
    weapons = Weapon.objects.all()

    default_weapons = {
        '주먹도끼': 1,
        '수상한 막대기': 7,
        '낡은 검': 5,
        '가벼운 물총': 3,
        '수학의 정석': 9,
    }
    
    if len(weapons) == 0:
        for weapon in default_weapons:
            Weapon.objects.create(
                name = weapon,
                power = default_weapons[weapon],
            )
        weapons = Weapon.objects.all()

    context = {
        'weapons': weapons,
    }
    return render(request, 'game/weapon_list.html', context)

# 게임은 하나의 캐릭터로 진행
def adventure_home(request):
    # 캐릭터 객체가 하나도 없는 경우
    if Character.objects.all().count() == 0:
        if request.method == 'POST':
            # Character의 weapon 필드에는 비어있는 객체가 저장될 수 있으므로 임시저장할 필요가 없음
            character_form = CharacterForm(request.POST)
            character_form.save()
            return redirect('game:adventure_home')
        else:
            character_form = CharacterForm()
        context = {
            'character_form': character_form,
        }
        return render(request, 'game/character_create.html', context)
    
    # 캐릭터가 생성된 경우
    else:
        # [코드 수정] Character 모델 중 id가 1인 캐릭터 객체를 가져옴
        # [코드 수정] None을 지우고 작성
        character = Character.objects.get(id=1)
        context = {
            'character': character,
        }
        # [코드 수정] character의 weapon 필드에 아무것도 저장되어 있지 않은 경우
        # [코드 수정] None을 지우고 작성
        if character.weapon == None:
            # [코드 수정] 'game/adventure_new.html'로 이동하도록 코드 작성
            # [코드 수정] None을 지우고 작성
            return render(request, 'game/adventure_new.html', context)
    return render(request, 'game/adventure_home.html', context)

# 캐릭터에게 랜덤으로 무기 장착
def weapon_get(request):
    # [코드 수정] Character 모델 중 id가 1인 캐릭터 객체를 가져옴
    # [코드 수정] None을 지우고 작성
    character = Character.objects.get(id=1)
    
    weapons = Weapon.objects.all()
    # [코드 수정] random 모듈의 choice 함수를 이용하여 selected_weapon 변수에 저장
    # [코드 수정] None을 지우고 작성
    selected_weapon = choice(weapons)
    
    character.weapon = selected_weapon
    character.save()

    context = {
        'character': character,
    }
    return render(request, 'game/adventure_home.html', context)

game/templates/game/adventure_home.html
{% extends 'base.html' %}

{% block body %}
  <h1>모험을 떠나봅시다.</h1>

  <p>당신은 <<{{character.weapon}}>>을 갖고 있습니다.</p>
  <!-- [코드 수정] 캐릭터가 갖고 있는 무기의 공격력을 표시 -->
  <!-- [코드 수정] ?를 지우고 작성 -->
  <p>{{character.weapon}}의 공격력은 {{character.weapon.power}}입니다.</p>

{% endblock %}

game/templates/game/adventure_new.html
{% extends 'base.html' %}

{% block body %}
  <h1>첫 모험을 시작합니다.</h1>

  <p>첫 무기는 랜덤으로 선택됩니다.</p>
  <p>무기를 받으시겠습니까?</p>
  <a href="{% url 'game:game_list' %}">돌아가기</a>
  <a href="{% url 'game:weapon_get' %}">무기 받기</a>
{% endblock %}

game/templates/game/character_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/character_create.css' %}">
{% endblock %}

{% block body %}
  <h1>캐릭터 생성</h1>

  <form action="" method="post">
    {% csrf_token %}
    {{character_form}}
    <input type="submit" value="생성">
  </form>
{% endblock %}

game/templates/game/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/game_list.css' %}">
{% endblock %}

{% block body %}
  <h1>게임 목록</h1>

  <ol>
    <li><p><a href="{% url 'game:rsp_select'%}">가위바위보 게임</a></p></li>
    <li><p><a href="{% url 'game:weapon_list'%}">무기 목록</a></p></li>
    <li><p><a href="{% url 'game:adventure_home' %}">장고캣의 모험(가제)</a></p></li>
  </ol>
{% endblock %}

game/templates/game/rsp_result.html
{% extends 'game/rsp_select.html' %}
{% load static %}

{% block rsp_head %}
  <link rel="stylesheet" href="{% static 'css/game/rsp_result.css' %}">
{% endblock %}

{% block rsp_body %}
  <h1>가위바위보 게임 결과</h1>
  
  <p>나는 <b>{{pick}}</b>를 선택했습니다.</p>
  <p>컴퓨터는 <b>{{com}}</b>를 선택했습니다.</p>

  <h2 class="rsp__result">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

game/templates/game/rsp_select.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/rsp_select.css' %}">
  {% block rsp_head %}
  {% endblock %}
{% endblock %}

{% block body %}

  {% block rsp_body %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="rsp__count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'game:rsp_reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp__button">
    <a href="{% url 'game:rsp_result' '가위' %}">가위</a>
    <a href="{% url 'game:rsp_result' '바위' %}">바위</a>
    <a href="{% url 'game:rsp_result' '보' %}">보</a>
  </div>
  
{% endblock %}

game/templates/game/weapon_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/weapon_form.css' %}">
{% endblock %}

{% block body %}
  <h1>무기 생성</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      <!-- [미션] views.py에서 생성된 weapon_form 배치 -->
      {{weapon_form.as_p}}
      <input type="submit" value="무기 생성">
    </div>
  </form>
{% endblock %}

game/templates/game/weapon_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/weapon_list.css' %}">
{% endblock %}

{% block body %}
  <h1>전체 무기 목록</h1>

  <ul>
    {% for weapon in weapons %}
      <li><p>{{weapon.name}} (공격력: {{weapon.power}})</p></li>
    {% empty %}
      <li><p>무기가 없습니다.</p></li>
    {% endfor %}
    <a class="button" href="{% url 'game:weapon_create' %}">무기 생성하기</a>
  </ul>
{% endblock %}